config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'table_view' => "home#table_view"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  include ApplicationHelper

  def index
    #ApplicationHelper
    json_parsing

  	new_array = []

  		if params[:search].nil?
        ### Kaminari pagination GEM
  			@paginatable_array = Kaminari.paginate_array(@books_data).page(params[:page]).per(6)
  		else

      ### FORM Get Request Views/Home/index
	  	  	@books_data.each do |book|
	  	  		if book["title"].include?(params[:search]) || book["year"].to_s.include?(params[:search]) || book["author"].include?(params[:search]) || book["isbn"].to_s.include?(params[:search])
	  	  			new_array << book
	  	  		end
	  		end

	  		@paginatable_array = Kaminari.paginate_array(new_array).page(params[:page]).per(6)			
  		end
  end

  def table_view



      if params[:search].nil?
        json_parsing
      else
          new_array = []
          ### FORM Get Request Views/Home/table_view
          json_parsing

          @books_data.each do |book|
            if book["title"].include?(params[:search]) || book["year"].to_s.include?(params[:search]) || book["author"].include?(params[:search]) || book["isbn"].to_s.include?(params[:search])
              new_array << book
            end
        end

        @books_data = new_array
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def json_parsing
		@books_data = HTTParty.get("https://skookum-test-api.herokuapp.com/api/v1/books")
		@books_data = @books_data.parsed_response 
	end

end

app/helpers/home_helper.rb
module HomeHelper

	def null?(info)
		if info == nil || info == ""
            "N/A"
        else
           info
        end
	end
end

app/views/home/index.html.erb
<%= render 'layouts/navbar' %>

<!-- Page Content -->
<div class="container">

    <div id="boxed-view">
            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-4"> 
                   <div>
                    <%= form_tag root_path, method: :get do %>
                        <div class="input-group custom-search-form">
                        <%= text_field_tag :search, nil, class: "form-control", placeholder: "Search Books...", style: "height: 50px;" %>
                        <span class="input-group-btn">
                        <%= button_tag(type: "submit",  class: "btn btn-default", style: "border-radius: 3px; border: 1px solid rgb(204,204,204); color: #fed136; background: black; height: 50px;") do %>
                            <i class="fa fa-search fa-fw"></i>
                        <% end %>
                        </span>
                        </div>
                    <% end %>
                    </div>
                </div>
                <div class="col-lg-8">
                    <h1 class="text-right" style="margin-top: 0;padding-top: 10px;">All Famous Books</h1>
                </div>
            </div>
            <hr class="border: 2px solid gray;">
            <!-- Projects Row -->
            <div class="row">
                <% @paginatable_array.each do |info| %>
                    <div class="col-sm-6 col-md-6 col-lg-4">
                        <div class="text-center">
                            <% if info["isbn"] == nil %>
                                <%= image_tag "no_cover.jpg", class: "img-responsive", style: "height: 250px; width: 60%; max-width: 100%;" %>
                            <% else %>
                                <%= image_tag "http://covers.openlibrary.org/b/isbn/#{null?(info["isbn"])}-L.jpg", class: "img-responsive", style: "height: 250px; width: 60%; max-width: 100%;" %>
                            <% end %>
                        </div>
        <!--                 <a href="#">

                            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                        </a> -->
                        <br>   
                          <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <td class="col-md-3 col-lg-3"><b>Title:</b></td>
                                    <td class="col-md-9 col-lg-9"><%= null?(info["title"]) %></td>
                                </tr>
                                <tr>
                                    <td class="col-md-3 col-lg-3"><b>Author:</b></td> 
                                    <td class="col-md-9 col-lg-9"><%= null?(info["author"]) %></td>
                                </tr>
                                <tr>
                                    <td class="col-md-3 col-lg-3"><b>Year:</b> </td>
                                    <td class="col-md-9 col-lg-9"><%= null?(info["year"]) %></td>
                                </tr>
                                <tr>
                                    <td class="col-md-3 col-lg-3"><b>ISBN:</b> </td>
                                    <td class="col-md-9 col-lg-9"><%= null?(info["isbn"]) %></td>
                                </tr>
                            </table>
                          </div>
                    </div>
                <% end %>
            </div>
            <!-- /.row -->

            <% if @paginatable_array.size > 6 %>
            <hr>
            <% end %>
            <div class="text-center">
                <%= paginate @paginatable_array, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered
                " %>
            </div>
        </div>

    <hr>

    <%= render 'layouts/footer' %>


</div>

app/views/home/table_view.html.erb
<%= render 'layouts/navbar' %>

<!-- Page Content -->
<div class="container">

    <div id="table-view">
            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-4"> 
                   <div>
                    <%= form_tag table_view_path, method: :get do %>
                        <div class="input-group custom-search-form">
                        <%= text_field_tag :search, nil, class: "form-control", placeholder: "Search Books...", style: "height: 50px;" %>
                        <span class="input-group-btn">
                        <%= button_tag(type: "submit",  class: "btn btn-default", style: "border-radius: 3px; border: 1px solid rgb(204,204,204); color: #fed136; background: black; height: 50px;") do %>
                            <i class="fa fa-search fa-fw"></i>
                        <% end %>
                        </span>
                        </div>
                    <% end %>
                    </div>
                </div>
                <div class="col-lg-8">
                    <h1 class="text-right" style="margin-top: 0;padding-top: 10px;">All Famous Books</h1>
                </div>
            </div>
                        <hr class="border: 2px solid gray;">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1">
                    <div class="table-responsive">
                        <table class="table table-striped" data-toggle="table">
                            <thead>
                                <tr>
                                    <th data-sortable="true">Title</th>
                                    <th data-sortable="true">Author</th>
                                    <th data-sortable="true">Year</th>
                                    <th data-sortable="true">ISBN</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @books_data.each do |book| %>
                                  <tr>
                                    <td><%= book["title"] %></td>
                                    <td><%= book["author"] %></td>
                                    <td><%= book["year"] %></td>
                                    <td><%= book["isbn"] %></td>
                                  </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    <hr>

    <%= render 'layouts/footer' %>


</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2018</p>
        </div>
    </div>
    <!-- /.row -->
</footer>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Famous Books</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li style="border: 1px solid gray; margin: 5px 0;"><% if current_page?(root_path) %>
                    <%= link_to "Table View", table_view_path, style: "padding: 5px; margin-top: 5px;" %>
                    <% else %>
                    <%= link_to "Boxed View", root_path,style: "padding: 5px; margin-top: 5px;" %>
                    <% end %>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>